-- CREATE DATABASE Project1;
USE Project1;
SELECT * FROM sales_data;


										-- DATA ANALYSIS AND KEY BUSINESS INSIGHTS --


-- Q1) Find the top 10 transactions by total sales value.

SELECT transactions_id , customer_id, gender, total_sale
FROM sales_data 
ORDER BY total_sale DESC LIMIT 10;

-- Q2 ) What is the total revenue generated by each product category?

SELECT category , SUM(total_sale)AS 'Total_Revenue'
FROM sales_data 
GROUP BY category
ORDER BY Total_Revenue DESC;

-- Q3) How many transactions were made by each gender?

SELECT gender ,COUNT(transactions_id) AS 'Total_Transaction'
FROM sales_data
GROUP BY gender
ORDER BY Total_Transaction;

-- Q4) What is the average price per unit for each product category?

SELECT category , ROUND(AVG(price_per_unit)) AS 'Avg_Price'.               -- > ROUND FUNCTION IMPORTANCE 
FROM sales_data
GROUP BY category 
ORDER BY Avg_Price DESC;

-- Q5) Which category has the highest total quantity sold?

SELECT category, ROUND(SUM(total_sale)) AS 'Total_Sales'
FROM sales_data
GROUP BY category 
ORDER BY Total_Sales DESC;


												-- Intermediate Questions ( 6-18 )  -- 


-- Q6) Identify the top 10 customers contributing the highest total revenue.

SELECT customer_id , SUM(total_sale) AS 'Total_sales'
FROM sales_data
GROUP BY customer_id
ORDER BY Total_sales 
DESC LIMIT 10;

-- Q7) Calculate the average order value (AOV) per category.

SELECT category, ROUND(AVG(total_sale)) AS 'Avg_Order_value'
FROM sales_data
GROUP BY category
ORDER BY Avg_Order_value DESC;

-- Q8) Segment customers into age groups (18–25, 26–35, 36–50, 51+) and find total revenue per segment     (CASE QUESTION ) 

SELECT  
CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
     WHEN age BETWEEN 26 AND 35 THEN '26-35'
		WHEN age BETWEEN 36 AND 50 THEN '36-50'                                         -- WE USE HERE FIELD FUNCTION TO SORT THE GROUP of AGE_GROUP -- 
        ELSE
        '51+'
END AS 'Age_Group',
SUM(total_sale) AS 'Total_Sale'
FROM sales_data
GROUP BY Age_Group 
ORDER BY FIELD ( Age_Group,'18-25','26-35','36-50','51+') ;


-- Q9) Find all categories where total revenue exceeds 150,000

SELECT category , SUM(total_sale) AS 'Total_Sales'
FROM sales_data
GROUP BY category
HAVING Total_Sales > 1500000;

-- Q10) Find customers who made more than 3 purchases. Show their transaction count and total spend           -- IMPORTANT QUESTION

SELECT customer_id , SUM(total_sale) AS 'Total_spend' , COUNT(transactions_id) AS 'Total_count'  
FROM sales_data
GROUP BY customer_id     															
HAVING COUNT(transactions_id) > 3
ORDER BY Total_spend DESC;

-- Q11) Calculate total revenue, total COGS, and gross profit for each category.

SELECT category, SUM(total_sale) AS 'Total_Revenue', SUM(cogs) AS 'Total_Cost', SUM(total_sale) - SUM(cogs) AS 'Gross_Profit'
FROM sales_data
GROUP BY category 
ORDER BY Gross_Profit DESC;

-- Q12) Find the total revenue contributed by female customers per category.       				-- GROUP BY 2 Categories 

SELECT category ,gender , SUM(total_sale) AS 'Total_Revenue'
FROM sales_data 
WHERE gender = 'Female'  
GROUP BY gender ,category               
ORDER BY Total_Revenue DESC;

-- Q13) For each category, show the highest single transaction value, the lowest, and the difference between them.

SELECT category, MAX(total_sale) AS 'Max_Transaction' , MIN(total_sale) AS 'Min_Transction', MAX(total_sale) - MIN(total_sale) AS 'Difference'
FROM sales_data 
GROUP BY category 
ORDER BY Difference DESC;

-- Q14) Calculate total revenue month-by-month. Which month had the highest sales?

SELECT MONTH(sale_date)AS 'Month' , SUM(total_sale) AS 'Total_Revenue_Month'
FROM sales_data
GROUP BY Month
ORDER BY Total_Revenue_Month ASC;

-- Q15) In a single query, find total revenue from Male vs Female customers for each category (pivot-style).        --GOOD CONCEPT--

SELECT category,
SUM( CASE WHEN gender = 'Male' THEN total_sale ELSE 0 END ) AS 'Male_Sales',
SUM( CASE WHEN gender = 'Female' THEN total_sale ELSE 0 END ) AS 'Female_Sales'    
FROM sales_data 
GROUP BY category
ORDER BY category DESC;

-- Q16) How many transactions occurred in each category during Q4 (October to December)?

SELECT category , MONTH(sale_date) AS 'Month' , COUNT(transactions_id) AS 'Total_count'     
FROM sales_data
WHERE MONTH(sale_date) BETWEEN 10 AND 12
GROUP BY category, month
ORDER BY category, Total_count DESC;

-- Q17) Find customers whose average transaction value is above 500. These are your premium segment.    -- IMPORTANT QUESTION -- 

SELECT customer_id, AVG(total_sale) AS 'Average_Value', COUNT(*) 
FROM sales_data 
GROUP BY customer_id
HAVING AVG(total_sale) > 500 
ORDER BY COUNT(*)  DESC;

-- Q18) Find all transactions where the total sales value is above the overall average transaction value.   -- HARD QUESTION -- 

SELECT transactions_id , customer_id , category, total_sale
FROM sales_data 
WHERE total_sale > (SELECT AVG(total_sale) FROM sales_data)
ORDER BY total_sale DESC;

-- Q19) Find categories whose average transaction value is higher than the overall average transaction value across all categories.

SELECT category,
  ROUND(AVG(total_sale)) AS avg_txn_value
FROM sales_data
GROUP BY category
HAVING AVG(total_sale) > (
  SELECT ROUND(AVG(total_sale)) FROM sales_data
);

-- Q20) Classify each customer as 'Platinum' (spend > 2000), 'Gold' (1000–2000), or 'Silver' (<1000) and count customers in each tier.

SELECT 
    CASE 
        WHEN total_spend > 2000 THEN 'Platinum'
        WHEN total_spend BETWEEN 1000 AND 2000 THEN 'Gold'
        ELSE 'Silver'
    END AS customer_tier,
    COUNT(*) AS customer_count
FROM (
    SELECT 
        customer_id,
        SUM(total_sale) AS total_spend
    FROM sales_data
    GROUP BY customer_id
) AS t
GROUP BY customer_tier
ORDER BY customer_count DESC;

